title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /:categories/:title/
baseurl:  # the subpath of your site, e.g. /blog
url: "http://krishnacodes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
    
# Author Settings
author: Phani Krishna # add your name
author-img: Phani-Krishna-pic-small.png # add your photo
about-author: I am a Deep Learning and Computer Vision Researcher. Our greatest glory is not in never falling, but in rising every time we fall - Confucius # add description
twitter: phanikrishnau # add your Twitter handle
facebook: phanikrishnau # add your Facebook handle
github: krishnacodes # add your Github handle
linkedin: phanikrishnau # add your Linkedin handle
email: krishnaphaniiitg@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
